server:
  port: 8084
  
spring:
  application:
    name: device-manager-service
  data:
     mongodb:
      host: ip
      port: 27017
      database: device-group
  cloud:
    consul:
      host: ip
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        healthCheckPath: /health
        preferIpAddress: true 
        ip-address: ip
logging:
  level:
    com.netas: DEBUG
